# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: apietrul <apietrul@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2015/08/18 11:07:31 by apietrul          #+#    #+#              #
#    Updated: 2015/08/18 11:41:40 by apietrul         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = tutoVid

SRC = main.c

all: $(NAME)

$(NAME):
	gcc -o $(NAME) $(SRC)

clean:
	/bin/rm -f *.o

fclean: clean
	/bin/rm -f $(name)

re: fclean all
